[package]
name = "imessage-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
pbkdf2 = "0.12.2"
rust-crypto = "0.2.36"
rustls = "0.21.5"
srp = "0.6.0"
reqwest = "0.11.18"
unicorn-engine = "2.0.1"
